{% set name = "opentelemetry-instrumentation-milvus" %}
{% set version = "0.49.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: efc1a062818c5b46862b4ec325b6db05f11ca74db71c48a2e5605d216633a197

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - poetry-core
  run:
    - python
    - opentelemetry-api >=1.38.0,<2.0.0
    - opentelemetry-semantic-conventions >=0.59b0
    - opentelemetry-instrumentation >=0.59b0
    - opentelemetry-semantic-conventions-ai >=0.4.13,<0.5
  run_constrained:
    - pymilvus >=2.4.1,<3.0.0

# Unable to run tests and check imports, pymilvus is not in the main channel.
test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.traceloop.com/openllmetry
  summary: OpenTelemetry Milvus instrumentation
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    This library allows tracing client-side calls to Milvus vector DB sent with the official Milvus library.
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction

extra:
  recipe-maintainers:
    - timkpaine
  skip-lints:
    - invalid_url
    - missing_imports_or_run_test_py
